### ISSUE TITLE
Recipe to demonstrate loading aus2200 data with chunking

### ISSUE THREAD

**Issue by andrewbrown31** [ACCESS-Community-Hub/atmosphere-cookbook#17]
I thought that a recipe demonstrating chunking could be useful. I have made one that shows how to load in a month of AUS2200 data, and calculate a rolling mean (which can be a large computation). Can I add it to the cookbook?

**Comment by navidcy** [comment]
https://atmosphere-cookbook.readthedocs.io/en/latest/Recipes/AUS2200_xarray_rolling.html

nice job!

**Comment by andrewbrown31** [comment]
Thanks! And thanks for helping me with the PR. Keen to contribute more recipes now

**Comment by navidcy** [comment]
> And thanks for helping me with the PR.

Anytime!

> Keen to contribute more recipes now

That's the spirit! ❤️
