### ISSUE TITLE
ACCESS Community Hub logo?

### ISSUE THREAD

**Issue by navidcy** [ACCESS-Community-Hub/atmosphere-cookbook#7]
Let's also add the ACCESS Community Hub logo on the README.

cc @heidinett

**Comment by heidinett** [comment]
@navidcy instead of the ACCESS Community Hub logo, could you please put the Atmosphere WG logo in the Readme.

**Comment by navidcy** [comment]
Great suggestion!

I opened the issue but I’ll let anyone from the community deal with it.

**Comment by heidinett** [comment]
Addressed in PR #9

**Comment by heidinett** [comment]
Addressed in PR https://github.com/ACCESS-Community-Hub/atmosphere-cookbook/pull/9
